<?php
/**
 * ApiuserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  GeoService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal GeoService
 *
 * Bumbal GeoService API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: jurgen@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace GeoService;

use \GeoService\Configuration;
use \GeoService\ApiClient;
use \GeoService\ApiException;
use \GeoService\ObjectSerializer;

/**
 * ApiuserApiTest Class Doc Comment
 *
 * @category Class
 * @package  GeoService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApiuserApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createApiUser
     *
     * create an ApiUser.
     *
     */
    public function testCreateApiUser()
    {
    }

    /**
     * Test case for deleteApiUser
     *
     * inactivate an ApiUser.
     *
     */
    public function testDeleteApiUser()
    {
    }

    /**
     * Test case for listApiUser
     *
     * retrieve a list of ApiUsers.
     *
     */
    public function testListApiUser()
    {
    }

    /**
     * Test case for retrieveApiUser
     *
     * retrieve a single ApiUser.
     *
     */
    public function testRetrieveApiUser()
    {
    }

    /**
     * Test case for updateApiUser
     *
     * update an ApiUser.
     *
     */
    public function testUpdateApiUser()
    {
    }
}
